In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from keras import Sequential, models
from keras.layers import Dense
from keras.losses import MeanSquaredLogarithmicError
from keras.optimizers import RMSprop

In [7]:
#Prepare dataset
n_sample = 10000
X = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]]*n_sample,dtype='float32')
Y = np.array([[0,0],[0,1],[0,1],[1,0],[0,1],[1,0],[1,0],[1,1]]*n_sample,dtype='float32')
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.1,shuffle=True)

In [9]:
#sample of dataset
print(x_train[503])
print(y_train[503])

[1. 0. 1.]
[1. 0.]


In [10]:
#model creation
model = Sequential()
model.add(Dense(units=3,activation='tanh',input_shape=(3,)))
model.add(Dense(units=2,activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 12        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 8         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(loss=MeanSquaredLogarithmicError(),optimizer=RMSprop(learning_rate=0.0001,momentum=0.9),metrics=['accuracy'])

In [12]:
#train model
history=model.fit(x_train,y_train,batch_size=32,epochs=5)

Epoch 1/5
2250/2250 [==============================] - 6s 2ms/step - loss: 0.1037 - accuracy: 0.7003
Epoch 2/5
2250/2250 [==============================] - 5s 2ms/step - loss: 0.0548 - accuracy: 0.8739
Epoch 3/5
2250/2250 [==============================] - 5s 2ms/step - loss: 0.0408 - accuracy: 0.8741
Epoch 4/5
2250/2250 [==============================] - 5s 2ms/step - loss: 0.0260 - accuracy: 0.8752
Epoch 5/5
2250/2250 [==============================] - 5s 2ms/step - loss: 0.0150 - accuracy: 0.8748


In [13]:
test_history=model.evaluate(x_test,y_test,verbose=1)

250/250 [==============================] - 1s 2ms/step - loss: 0.0093 - accuracy: 0.8821


In [14]:
print(np.around(model.predict([[0,1,1]])))

[[1. 0.]]


In [15]:
print(np.around(model.predict([[0,1,0]])))

[[0. 1.]]


In [16]:
print(np.around(model.predict([[0,0,1]])))

[[0. 1.]]


In [17]:
print(np.around(model.predict([[1,1,1]])))

[[1. 1.]]


In [18]:
from random import randint

In [97]:
max_digit = 8
number_A = np.array([randint(0,pow(2,max_digit)/2)],dtype='uint8')
number_B = np.array([randint(0,pow(2,max_digit)/2)],dtype='uint8')
print(number_A,number_B)

[27] [71]


In [98]:
binary_A = np.unpackbits(number_A,axis=0)
binary_B = np.unpackbits(number_B,axis=0)
print(binary_A,binary_B)

[0 0 0 1 1 0 1 1] [0 1 0 0 0 1 1 1]


In [99]:
binary_A = np.flip(binary_A)
binary_B = np.flip(binary_B)
print(binary_A,binary_B)

[1 1 0 1 1 0 0 0] [1 1 1 0 0 0 1 0]


In [100]:
binary_C = np.zeros(shape=(max_digit,),dtype='uint8')
carry=0
for i in range(max_digit):
    carry_a_b = np.array([[carry,binary_A[i],binary_B[i]]],dtype='float32')
    out = model.predict(carry_a_b)
    carry=out[0][0]
    binary_C[i]=np.uint8(np.around(out[0][1]))
    print(np.around(carry_a_b),np.around(out))

[[0. 1. 1.]] [[1. 0.]]
[[1. 1. 1.]] [[1. 1.]]
[[1. 0. 1.]] [[1. 0.]]
[[1. 1. 0.]] [[1. 0.]]
[[1. 1. 0.]] [[1. 0.]]
[[1. 0. 0.]] [[0. 1.]]
[[0. 0. 1.]] [[0. 1.]]
[[0. 0. 0.]] [[0. 0.]]


In [101]:
binary_C = np.flip(binary_C)
number_C = np.packbits(binary_C)
print(binary_C)
print(number_C)

[0 1 1 0 0 0 1 0]
[98]
