In [153]:
import numpy as np
from sklearn.model_selection import train_test_split
from keras import Sequential, models
from keras.layers import Dense
from keras.losses import MeanSquaredError,MeanSquaredLogarithmicError,CosineSimilarity
from keras.optimizers import Adam,RMSprop,Ftrl,SGD

In [154]:
n_sample = 10000
X = np.array([[0,0],[0,1],[1,0],[1,1]]*n_sample,dtype='float32')
Y = np.array([[0,0],[0,1],[0,1],[1,0]]*n_sample,dtype='float32')
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.1,shuffle=True)

In [155]:
print(x_train[502])
print(y_train[502])

[0. 1.]
[0. 1.]


In [156]:
model = Sequential()
model.add(Dense(units=3,activation='tanh',input_shape=(2,)))
model.add(Dense(units=2,activation='sigmoid'))
model.summary()

Model: "sequential_16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_30 (Dense)             (None, 3)                 9         
_________________________________________________________________
dense_31 (Dense)             (None, 2)                 8         
Total params: 17
Trainable params: 17
Non-trainable params: 0
_________________________________________________________________


In [157]:
model.compile(loss=MeanSquaredLogarithmicError(),optimizer=RMSprop(learning_rate=0.0001,momentum=0.9),metrics=['accuracy'])

In [158]:
history=model.fit(x_train,y_train,batch_size=32,epochs=5)

Epoch 1/5
1125/1125 [==============================] - 3s 3ms/step - loss: 0.1196 - accuracy: 0.5203
Epoch 2/5
1125/1125 [==============================] - 3s 2ms/step - loss: 0.0768 - accuracy: 0.5820
Epoch 3/5
1125/1125 [==============================] - 3s 2ms/step - loss: 0.0471 - accuracy: 0.7543
Epoch 4/5
1125/1125 [==============================] - 3s 2ms/step - loss: 0.0163 - accuracy: 0.7519
Epoch 5/5
1125/1125 [==============================] - 2s 2ms/step - loss: 0.0033 - accuracy: 0.7505


In [159]:
test_history = model.evaluate(x_test,y_test,verbose=1)

125/125 [==============================] - 0s 2ms/step - loss: 8.4558e-04 - accuracy: 0.7383


In [160]:
print(np.around(model.predict([[0,1]])))

[[0. 1.]]


In [161]:
print(np.around(model.predict([[1,1]])))

[[1. 0.]]


In [162]:
print(np.around(model.predict([[1,0]])))

[[0. 1.]]


In [163]:
print(np.around(model.predict([[0,0]])))

[[0. 0.]]


In [164]:
model.evaluate([[0,0]],[[0,0]],verbose=2)

1/1 - 0s - loss: 8.4873e-04 - accuracy: 0.0000e+00


[0.0008487306185998023, 0.0]